package changelog

import (
	"fmt"
	"math/rand"
	"testing"

	"github.com/lkshrk/ops-pilot/internal/adapters/github"
)

type sweepEntry struct{ tag, truth string }

func sweepInRange(truth, from, to string) bool {
	if truth == "" {
		return false
	}
	a, ok := compare(truth, from)
	if !ok || a <= 0 {
		return false
	}
	b, ok := compare(truth, to)
	return ok && b <= 0
}

// history returns a full listing newest first, generated by publishing on the
// given concurrent version lines in random order, plus the truths needed to
// score a verdict.
func history(seed int64, n int, lines [][3]int, tagf func(string) string) []sweepEntry {
	rng := rand.New(rand.NewSource(seed))
	cursor := append([][3]int(nil), lines...)
	var oldestFirst []sweepEntry
	for i := 0; i < n; i++ {
		l := rng.Intn(len(cursor))
		cursor[l][2]++
		truth := fmt.Sprintf("%d.%d.%d", cursor[l][0], cursor[l][1], cursor[l][2])
		oldestFirst = append(oldestFirst, sweepEntry{tag: tagf(truth), truth: truth})
	}
	out := make([]sweepEntry, 0, n)
	for i := len(oldestFirst) - 1; i >= 0; i-- {
		out = append(out, oldestFirst[i])
	}
	return out
}

func plain(v string) string    { return "v" + v }
func monorepo(v string) string { return "sonarr-" + v }
func dated(v string) string    { return v }

// A verdict is wrong when a truncated read is accepted while the pages below the
// cut still hold a release inside the range. Scored against the full history the
// prefix was cut from, over every range the prefix can express.
func TestNoTruncatedReadIsAcceptedWhileTheRangeContinuesBelowTheCut(t *testing.T) {
	singleLine := [][3]int{{1, 0, 0}}
	twoLines := [][3]int{{1, 0, 0}, {1, 1, 0}}
	lts := [][3]int{{0, 9, 0}, {1, 2, 0}}
	fourLines := [][3]int{{1, 0, 0}, {1, 1, 0}, {1, 2, 0}, {0, 9, 0}}

	for _, shape := range []struct {
		name  string
		lines [][3]int
		tagf  func(string) string
	}{
		{name: "one line", lines: singleLine, tagf: plain},
		{name: "one line with monorepo tags", lines: singleLine, tagf: monorepo},
		{name: "one line with bare date-like tags", lines: singleLine, tagf: dated},
		{name: "two concurrent lines", lines: twoLines, tagf: plain},
		{name: "an LTS line beside the newest", lines: lts, tagf: plain},
		{name: "four concurrent lines", lines: fourLines, tagf: plain},
		{name: "four concurrent lines with monorepo tags", lines: fourLines, tagf: monorepo},
	} {
		t.Run(shape.name, func(t *testing.T) {
			t.Parallel()
			accepts, sound, refusals := 0, 0, 0
			for seed := int64(1); seed <= 8; seed++ {
				full := history(seed, 3000, shape.lines, shape.tagf)
				for _, cut := range []int{100, 500, 1000, 1500} {
					prefix := make([]github.Release, 0, cut)
					for _, e := range full[:cut] {
						prefix = append(prefix, github.Release{TagName: e.tag})
					}
					for _, start := range []int{0, 1, 2, 5, 25, 100, 300, 600, 900, cut - 10, cut - 5, cut - 1, cut, cut + 50, cut + 500} {
						if start < 0 || start >= len(full) {
							continue
						}
						from, to := full[start].truth, full[0].truth
						accepted := accountsForRange(prefix, from, to)
						omitted := 0
						for _, e := range full[cut:] {
							if sweepInRange(e.truth, from, to) {
								omitted++
							}
						}
						switch {
						case accepted && omitted > 0:
							t.Errorf("cut=%d from=%s to=%s accepted while %d in-range releases sit below the cut",
								cut, from, to, omitted)
						case accepted:
							accepts, sound = accepts+1, sound+1
						default:
							refusals++
						}
					}
				}
			}
			t.Logf("%d accepts, all sound (%d), %d refusals", accepts, sound, refusals)
		})
	}
}

// The relief has to survive where it was measured: a single-line history whose
// range start sits just inside the cut still resolves, or the >budget dependency
// is back to holding on every bump.
func TestASingleLineHistoryIsStillAcceptedRightUpToTheCut(t *testing.T) {
	for _, start := range []int{1, 5, 100, 900, 990, 995, 998, 999} {
		var prefix []github.Release
		for minor := 1999; minor > 999; minor-- {
			prefix = append(prefix, github.Release{TagName: fmt.Sprintf("v1.%d.0", minor)})
		}
		from, to := fmt.Sprintf("1.%d.0", 1999-start), "1.1999.0"
		if !accountsForRange(prefix, from, to) {
			t.Errorf("a single-line history refused a range starting %d releases back (from=%s)", start, from)
		}
	}
	var prefix []github.Release
	for minor := 1999; minor > 999; minor-- {
		prefix = append(prefix, github.Release{TagName: fmt.Sprintf("v1.%d.0", minor)})
	}
	if accountsForRange(prefix, "1.999.0", "1.1999.0") {
		t.Error("a range starting one release past the cut was accepted")
	}
}

// The shapes named in the refutation, each as one listing rather than a sweep.
func TestTheNamedInversionShapesAreRefused(t *testing.T) {
	newestLine := func(lowest int) []github.Release {
		var out []github.Release
		for minor := 999; minor >= lowest; minor-- {
			out = append(out, github.Release{TagName: fmt.Sprintf("v1.%d.0", minor)})
		}
		return out
	}
	ltsBelow := append(newestLine(900), github.Release{TagName: "v0.9.50"}, github.Release{TagName: "v0.9.49"})
	ltsInside := append([]github.Release{{TagName: "v1.999.0"}, {TagName: "v0.9.50"}}, newestLine(900)[1:]...)
	backportAfterMajor := append([]github.Release{{TagName: "v2.0.0"}, {TagName: "v1.500.0"}}, newestLine(900)...)
	nightly := append([]github.Release{{TagName: "nightly-build-alpha"}}, newestLine(900)...)

	for _, testCase := range []struct {
		name     string
		releases []github.Release
		from, to string
		want     bool
	}{
		{name: "an LTS line below the newest, range start paged away", releases: ltsBelow, from: "1.100.0", to: "1.999.0"},
		{name: "an LTS release inside the run, range start paged away", releases: ltsInside, from: "1.100.0", to: "1.999.0"},
		{name: "an LTS line below the newest, range start present", releases: ltsBelow, from: "1.900.0", to: "1.999.0", want: true},
		{name: "an LTS release inside the run, range start present", releases: ltsInside, from: "1.900.0", to: "1.999.0"},
		{name: "a backport published after the next major", releases: backportAfterMajor, from: "1.400.0", to: "1.999.0"},
		{name: "a rolling tag the range cannot place", releases: nightly, from: "1.900.0", to: "1.999.0"},
		{name: "a wrong annotation whose newest release predates the range", releases: newestLine(900), from: "2024.1.0", to: "2024.2.0"},
	} {
		t.Run(testCase.name, func(t *testing.T) {
			if got := accountsForRange(testCase.releases, testCase.from, testCase.to); got != testCase.want {
				t.Fatalf("accountsForRange = %v, want %v", got, testCase.want)
			}
		})
	}
}

// A version inversion spanning the whole read window leaves a strictly ordered
// prefix with the anchor present, so any prefix-only rule accepts it; closing it
// needs the whole history, not a stronger prefix rule.
func TestAWholeWindowVersionInversionIsAcceptedUnsoundBecauseNoPrefixRuleCanCloseIt(t *testing.T) {
	tail := func() []github.Release {
		var out []github.Release
		for patch := 900; patch >= 1; patch-- {
			out = append(out, github.Release{TagName: fmt.Sprintf("v1.1.%d", patch)})
		}
		return out
	}
	belowCut := []string{"v2.0.4", "v2.0.3", "v2.0.2", "v2.0.1", "v2.0.0"}
	from, to := "1.2.3", "2.0.5"

	for _, anchor := range []string{"v1.2.3", "v1.2.3+build7"} {
		t.Run(anchor, func(t *testing.T) {
			prefix := append([]github.Release{{TagName: "v2.0.5"}, {TagName: anchor}}, tail()...)
			if !accountsForRange(prefix, from, to) {
				t.Fatalf("prefix (anchor %s) is accepted by design; the residual is that it is", anchor)
			}
			omitted := 0
			for _, tag := range belowCut {
				if sweepInRange(tag, from, to) {
					omitted++
				}
			}
			if omitted == 0 {
				t.Fatal("the pin needs an in-range release below the cut to demonstrate the unsound accept")
			}
		})
	}
}

// The C-M75 relief is narrower than "a single ordered line": a stable patch
// published between two prereleases of the next version breaks the version-order
// run, so a truncated read of it holds even though the range start is present.
func TestAStablePatchPublishedBetweenTwoPrereleasesHoldsRatherThanResolvingTruncated(t *testing.T) {
	prefix := []github.Release{
		{TagName: "1.5.0-rc2"}, {TagName: "1.4.1"}, {TagName: "1.5.0-rc1"}, {TagName: "1.4.0"},
	}
	if accountsForRange(prefix, "1.4.0", "1.4.1") {
		t.Fatal("a stable patch interleaved with the next version's prereleases must hold, not resolve")
	}
}
